version: '2'
 
services:
  app:
    build:
      context:  ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
    links:
      - proxy
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
   